### ISSUE TITLE
mouse wheel on titlebar: option for take-to-desktop

### ISSUE THREAD

**Issue by dobkeratops** [raspberrypi-ui/openbox-stretch#2]
Personally I like using the mouse-wheel for *take window to next desktop* / *take window to previous desktop* ('take to desktop' means a combination of 'send window' plus switching to that desktop). I found this option in 'sawfish' and it's sadly not so common (I did fork a version of xfwm to do it, but I tend to lose tweaks that aren't integrated in a mainline install)

Would it be possible to add an option for this in the configuration ? (I would also argue it's a much better default, but I'd settle for it being available).

 - it's very intuitive, because you already associate the mousewheel with desktop switching when used on the desktop - and allows you to better leverage the desktops without fiddly use of the menu or 'sticky'  icon; the usual default of 'rollup/rolldown' wastes the 'up/down' nature of the mousewheel (it could be a toggle), and the panel does a similar job (plus when it's so easy to move windows between desktops, it still easy to 'move it out of the way' and get back to seeing everything else, with a simple mouse movement)

Historically some have complained that 'multiple desktops' are extraneous, but the mainstream commercial OS's have actually followed linux's lead and added support for them (the mac in particular has extremely good trackpad gestures for using them). I would argue it's best to replace the 'hide'&'show desktop' functionality with more intuitive desktop manipulation, which the mouse wheel use I suggest does achieve. ( a nice idea in gnome shell which could be retrofitted is to always ensure there's an 'empty desktop', which does the job of having 'show desktop', or 'hide others' - because you can always 'take the window to the empty desktop' to just focus on it, or switch to the empty desktop to start over)

**Comment by spl237** [comment]
If openbox actually supports that behaviour, it is easy enough for someone who wants it to add by changing the settings in the openbox configuration XML file with a text editor - it'll be something like 

```
<mousebind button="Up" action="Click">
      <action name="DesktopPrevious"/>
    </mousebind>
    <mousebind button="Down" action="Click">
      <action name="DesktopNext"/>
    </mousebind>

```
The GUI configuration options are deliberately selected to be the bare minimum that most users would want to change - this option, while useful to some, is too specialised to be worth adding as a generic option in the GUI.

**Comment by dobkeratops** [comment]
seems to be a rather rapid dismissal of the issue.. have you ever tried using a DE with this option ?

remember that once 'multiple desktops' were considered too specialised - yet (many years later) both windows and mac have them. What I find today is the mac has the best window/desktop management, and the closest linux comes is when this option is available

**Comment by dobkeratops** [comment]
I note there's an option for "double click on title bar -> maximise the window / shades the window"

How about enabling the mouse wheel for take-to-desktop if the user chooses that (basically you have 2 modes for window behaviour already - you could make more holistic choices on the overall functions.. if you chose 'double-click for shade', you're wasting the mouse wheel by *also* having that for shade)

**Comment by spl237** [comment]
> seems to be a rather rapid dismissal of the issue.. have you ever tried using a DE with this option ?

Yes. 

I don't like them. They are confusing for beginners, and are only actually desired by a small number of advanced users. Neither Windows nor Mac particularly advertise their multiple desktop support for this very reason.

It is easy enough for an experienced user to reinstate this functionality if they want it. It will not be supported in the default configuration.
