### ISSUE TITLE
" It is far too easy to open an application, accidentally hit a button to switch to a new desktop, and have everything vanish for no reason. This is not helpful, particularly for beginners."

### ISSUE THREAD

**Issue by dobkeratops** [raspberrypi-ui/openbox-stretch#4]
arghhh. why are you shutting the discussion down? 
I'm not arguing for it to be enabled by default! 

You're thinking about multi-desktops *the way they're implemented in old linux DE's*, and there has been evolution since.

**In the mac, it's *fully integrated with maximize/fullscreen*.** 

>>'accidentally hit a button, have everything disappear'
 - I understand this hazard. 

But in newer workflows this hazard disappears, because the means of getting the windows back is clearer. They also do 'more with less' on the panel by integration the launchers with 'indication of active windows' (the dots under the launcher icon showing the instances, or the 

currently the taskbar (and alt-tab menus) are setup to only show stuff from the current desktop (so your windows *disappear*. 
**All it would take is showing stuff from all desktops** (and how about if it was just sorted for the current desktop first). Then if it runs out of space, prioritise based on the current desktop. Or how about the opposite.. only showing hidden *and other desktop windows* on the panel ('i minimised it.. or i switched desktop -> but it appears on the panel..)

How about if it only shows the desktop switcher when the number of desktops is >1. Similarly show all the windows on the panel (or use one of these docks that integrates instances with launchers..) How about if it worked like gnome-shell where _it manages the desktops for you_, then you wouldn't need to see/learn extra controls ('create desktop/remove desktop').

Gnome Shell is pretty interesting with it's graphical transitions. But I dont think you need to go *so* far to make something better; it just takes a few *integrated* tweaks. Thats why I'm talking here rather than just forking something.

>> it's an anachronism from a time...

Apple (the UI masters) and Microsoft both disagree, they followed linux's lead in providing multiple desktop support, *and improved on it*, with very logical integration with the maximise feature. maximised window = desktop holding a fullscreen app; hence less need for seperate controls for desktops/windows.

**Comment by spl237** [comment]
I have now explained our position on this issue multiple times. Your opinion differs from ours - that's fine. It doesn't mean we are obliged to change our position.

If there are code changes required to achieve what you want, feel free to push them to the parent LXDE environment; they will then permeate into Raspbian when we move to Buster. But from what I have seen, the functionality you want can be added by modifying the Openbox configuration files; there are no code changes required. Feel free to customise your own system however you see fit. We will not be customising Raspbian to improve multiple desktop support, for the reasons I have already explained several times.
